# Generated by Django 5.2.17 on 2026-08-09 20:50

import django_fundamentals.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_fundamentals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Square images work best. Leave empty to use your initials.",
                storage=django_fundamentals.storage.AvatarStorage(),
                upload_to="avatars/",
            ),
        ),
    ]
